# Site settings
title: "Shane Weaver"
description: "Human Software Engineer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Shane B. Weaver"
resume_title:                   "Human Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "shanebweaver@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "253.355.4790"
resume_contact_address:         "Woodinville, WA"

resume_header_contact_info:     "Woodinville, WA • 253.355.4790 • shanebweaver@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<ul>
                        <li>Developer lead for the <a href="https://docs.microsoft.com/en-us/graph/toolkit/overview">Microsoft Graph Toolkit</a> open source project.</li>
                        <li>Award winning Windows 10 app developer with expertise in 10 foot UX, VOD services, and DRM.</li>
                        <li>Over 10 years of experience in software design, analysis, and full stack development using C#/XAML, JavaScript/HTML, and open source web technologies.</li>
                        <li>Team lead and Scrum Master experience, managing small to medium size dev/QA teams.</li>
                        <li>Extremely versatile. Experience in a variety of environments and languages in positions covering software engineering, product development, development operations, and developer support.</li>
                      </ul>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
# resume_section_education:       true
resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/shanebweaver"
  # resume_twitter_url:         ""
  # resume_dribbble_url:        ""
  # resume_facebook_url:        ""
  resume_linkedin_url:          "https://www.linkedin.com/in/shanebweaver"
  # resume_instagram_url:       ""
  resume_website_url:           "http://www.shanebweaver.com"
  # resume_medium_url:          ""
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
